### ISSUE TITLE
`set_value` doesn't  work.

### ISSUE THREAD

**Issue by Jerrody** [imbolc/tower-cookies#11]
Should change the value to login `String` and password `String`, but nothing happens.

```rs
async fn register_new_account(
    Form(new_account): Form<Account>,
    Extension(pool): Extension<PgPool>,
    cookie: Cookies,
) -> impl IntoResponse {
    sqlx::query!(
        "INSERT INTO accounts (login, password) VALUES ($1, $2)",
        new_account.login,
        new_account.password
    )
    .execute(&pool)
    .await
    .unwrap();

    println!("SUS! {} | {}", new_account.login, new_account.password);
    cookie.get("login").unwrap().set_value(new_account.login); 
    cookie.get("password").unwrap().set_value(new_account.password);

    Redirect::to(Uri::from_static("/"))
}
```

Lines where I try to change a value.
```rs
cookie.get("login").unwrap().set_value(new_account.login); 
cookie.get("password").unwrap().set_value(new_account.password);
```

**Result after handler work:**
![image](https://user-images.githubusercontent.com/68968657/156931337-625c4d9f-7b3e-4014-800d-37fd88835094.png)

**Comment by imbolc** [comment]
Here's an example how to set cookies: https://github.com/imbolc/tower-cookies/blob/main/examples/hello_world.rs

**Comment by Jerrody** [comment]
> Here's an example how to set cookies: https://github.com/imbolc/tower-cookies/blob/main/examples/hello_world.rs

Would be great if we could just use this method like this:
```rs
// Some like this.
cookie.get("login").unwrap().set_value(new_account.login).add(); 
```

**Comment by Jerrody** [comment]
I can make a later PR if you wanna. It would be more comfortable

**Comment by imbolc** [comment]
Thank you, but I don't see how would it make api and cleaner or shorter. Eg if you get rid of `unwraps` your code becomes:

```rust
if let Some(c) = cookies.get("login") {
    cookie.set_value(new_account.login);
} else {
    cookies.add(Cookie::new("login", new_account.login));
}
```
Instead you can just use:
```rust
cookies.add(Cookie::new("login", new_account.login));
```
