### ISSUE TITLE
[Question] How to remove cookies?

### ISSUE THREAD

**Issue by Zerowalker** [imbolc/tower-cookies#14]
I am having some problem figuring out how to remove cookies.

Cause you need to have the cookie in order to remove it, which to me is weird as i would expect to remove it by it's name.
But if you get the cookie beforehand you can't use that cookie to remove it cause of lifetime issues.
Are you supposed to just create a dummy cookie like in the Counter example?

```
    async fn handler(Extension(cookies): Extension<Cookies>) {
        let key = KEY.get().unwrap();
        let private_cookies = cookies.signed(key);
        cookies.remove(Cookie::new(COOKIE_NAME, ""));
    }
```

**Comment by imbolc** [comment]
Hey :)

Yep, a dummy cookie is ok. I see your point, but `tower-cookies` is just a tokio middleware around [cookie](https://docs.rs/cookie/) crate, I guess they have their reasons for this kind of api. Here's the description of its [`remove`](https://docs.rs/cookie/latest/cookie/struct.CookieJar.html#method.remove) method. Maybe [make_removal](https://docs.rs/cookie/latest/cookie/struct.Cookie.html#method.make_removal) is what you're looking for.

**Comment by Zerowalker** [comment]
Hey :)

Thanks for the quick response.
It indeed looks like `make_removal` is what i am looking for.
Is it possible to expose it from `tower-cookies`?
same goes for `SameSite`, cause then one wouldn't need to have the `cookie` crate in parallel.

**Comment by imbolc** [comment]
> But then i still use the cookie i grabbed which doesn't work cause of the lifetime right?

Right. I don't see an obvious way to fix this. And also I don't remember ever needing `make_removal`, it feels always easier to just "remove" potentially non-existing cookie (it won't even create unnecessary header if the cookie doesn't exist as there won't be any "delta").

As for removing cookies by name, it certainly feels more intuitive, thank you for the suggestion. Could you review the changes before I merge it: https://github.com/imbolc/tower-cookies/commit/56a1fc359e5005ee6c1e83c11833086bf29bf36a

**Comment by imbolc** [comment]
Hmm... I don't think it's a correct approach though as [cookie::CookieJar::remove](https://docs.rs/cookie/latest/cookie/struct.CookieJar.html#method.remove) says:

> To properly generate the removal cookie, cookie must contain the same path and domain as the cookie that was initially set.

So I guess we should first check if the cookie is there and use its path and domain while removing it just by name.

**Comment by imbolc** [comment]
I think it's done: https://github.com/imbolc/tower-cookies/pull/15

@davidpdrsn @programatik29 would one of you guys have a few minutes to review it? It makes it possible to remove cookies by name, thakns :pray:

**Comment by Zerowalker** [comment]
Oh you work quick.
Good catch with the `Path` part, otherwise it would be quite prone to "error".

Also, i remove some cookies in my error handler, but i don't know how to use the `tower-cookies` there as you just get access to the error and make a response.
Is there something i am might be missing you think, or might this just be a special case where i gotta use `headers` directly?

Thanks:)

**Comment by davidpdrsn** [comment]
> Also, i remove some cookies in my error handler, but i don't know how to use the tower-cookies there as you just get access to the error and make a response.

What specifically do you mean by "error handler"? Do you mean using `HandleErrorLayer`, because that also supports running extractors. `async fn handle_error(cookies: tower_cookies::Cookies, err: axum::BoxError)` should work.

**Comment by imbolc** [comment]
Or in case of a middleware, where you have only a request you can use `Cookies::from_request`: https://github.com/imbolc/tower-cookies/blob/353003051701d3e0d728301614bde80201e2a875/examples/counter-extractor.rs#L22

**Comment by Zerowalker** [comment]
It's a `impl IntoResponse for MyError`
Perhaps no the correct way to do it?

**Comment by imbolc** [comment]
Jar is kept in request extensions, so no access to request - no cookies :)

**Comment by Zerowalker** [comment]
make sense:)
So can i "solve" this by using a middleware or?
The purpose of the error handling is to be able to use `Result`.
But yeah this is clearly off topic so feel bad taking up even more of your time, so no need to really answer this.

**Comment by imbolc** [comment]
If you have request where you raise the error, you can process cookies there:
```rust
enum Error {
    LogOut
}

impl Error {
    log_out(req: RequestParts) -> Self {
        let cookies = Cookies::from_request(req).await?;
        ...
        Self::LogOut
    }
}
```

If you don't have the request, you can put something into the response extensions. And then in a middleware you can check the extensions and change cookies. Maybe there's a simpler way of doing this, you can ask in the axum discord: https://discord.com/channels/500028886025895936/870760546109116496

**Comment by imbolc** [comment]
So I guess we stick with the current behavior :)
