### ISSUE TITLE
Question: How to store the signed cookie key?

### ISSUE THREAD

**Issue by Zerowalker** [imbolc/tower-cookies#27]
If i understand it correctly you always retrieve `Cookie` in the handler/middleware.
Then in order to use the signed variant you need to specify a key afterwards each time.

In my case i generate a global random key that's set inside a `OnceCell<tower_cookies::Key>`,
and then just `cookies.signed(KEY.get().unwrap())` each time.

This seems a bit "messy" so was wondering if there's another approach here, or perhaps mine is just a bad idea to begin with.

Could one perhaps setup the `SignedCookie` to be available directly?

Thanks:)

**Comment by imbolc** [comment]
If I understand your concern, you can make an extractor for this "messy" stuff

**Comment by Zerowalker** [comment]
Ah, will look into that, thanks:)!
