### ISSUE TITLE
Request: Explain/document the logic behind the cookie jar approach?

### ISSUE THREAD

**Issue by jakajancar** [imbolc/tower-cookies#28]
Hey @imbolc,

Can you explain (or even document) what is the idea behind the cookie jar in this middleware?

The way I understand it, a service is a `f(req) -> res`. Cookies come in on requests (`Cookie` header) and go out on responses (`Set-Cookie` header) like any other thing comes in or goes out. I would expect tooling on `Request` to read cookies and on `Response` to set them. I understand the concept of a cookie jar for a client that needs to store state between requests, but what is the point of a per-request cookie jar on a server?

Also, isn’t it odd that handlers then return a part of their response via the return value and a part via state mutation on an argument?

Is the purpose that if a handler sets a cookie, but then the response is never sent to the client because some middleware intercepts it, the cookie still gets set? What’s an example case for that?

Thanks!

**Comment by imbolc** [comment]
Hey :)

You can look at it from the session mental model perspective.

Imagine a few layers dealing with cookies, each of them wants to read and set some. Without this approach:

- each of them would have to re-parse the cookie header
- if a layer wants too look at the cookies changes made by previous ones it would have to parse response headers
